# Generated by Django 5.0b1 on 2023-11-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("title", models.TextField()),
                ("date", models.DateTimeField()),
                ("url", models.TextField()),
                ("author", models.TextField()),
                ("author_url", models.TextField()),
                ("hub", models.TextField()),
                ("post_id", models.PositiveIntegerField()),
            ],
        ),
    ]
