# Generated by Django 5.0b1 on 2023-11-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="date",
            field=models.TextField(),
        ),
    ]
